name: 'fea_adventure_works'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fea_adventure_works:
    staging:
      +materialized: view
    marts:
      +materialized: table
      dimensions:
        +materialized: table
      facts:
        +materialized: table